project_id = "jpujaqqvbfwvtzsxvxap"

[functions.process-email-queue]
verify_jwt = true

[functions.send-transactional-email]
verify_jwt = true

[functions.preview-transactional-email]
verify_jwt = false

[functions.handle-email-unsubscribe]
verify_jwt = false

[functions.handle-email-suppression]
verify_jwt = false
[functions.fulfill-order]
verify_jwt = false

[functions.validate-discount]
verify_jwt = false

[functions.newsletter-subscribe]
verify_jwt = false
